spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:mysql://localhost:6033/users_mysql
    username: root
    password: 123456

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

