services:
  user-mysql:
    image: mysql:8.4.0
    container_name: users-mysql
    hostname: users-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: users_mysql
    ports:
      - '6033:3306'
  redis-todo-app:
    image: redis:7.2.5
    container_name: redis-todo-app
    hostname: redis-todo-app
    ports:
      - '6379:6379'
